/**
 * Voting Redux Action Types
 * Election Management System
 */

// ============================================================================
// ACTION TYPES
// ============================================================================

// Vote Counts
export const GET_VOTE_COUNTS_REQUEST = 'voting/GET_VOTE_COUNTS_REQUEST';
export const GET_VOTE_COUNTS_SUCCESS = 'voting/GET_VOTE_COUNTS_SUCCESS';
export const GET_VOTE_COUNTS_FAILURE = 'voting/GET_VOTE_COUNTS_FAILURE';

export const CREATE_VOTE_COUNT_REQUEST = 'voting/CREATE_VOTE_COUNT_REQUEST';
export const CREATE_VOTE_COUNT_SUCCESS = 'voting/CREATE_VOTE_COUNT_SUCCESS';
export const CREATE_VOTE_COUNT_FAILURE = 'voting/CREATE_VOTE_COUNT_FAILURE';

export const UPDATE_VOTE_COUNT_REQUEST = 'voting/UPDATE_VOTE_COUNT_REQUEST';
export const UPDATE_VOTE_COUNT_SUCCESS = 'voting/UPDATE_VOTE_COUNT_SUCCESS';
export const UPDATE_VOTE_COUNT_FAILURE = 'voting/UPDATE_VOTE_COUNT_FAILURE';

export const DELETE_VOTE_COUNT_REQUEST = 'voting/DELETE_VOTE_COUNT_REQUEST';
export const DELETE_VOTE_COUNT_SUCCESS = 'voting/DELETE_VOTE_COUNT_SUCCESS';
export const DELETE_VOTE_COUNT_FAILURE = 'voting/DELETE_VOTE_COUNT_FAILURE';

export const VERIFY_VOTE_COUNT_REQUEST = 'voting/VERIFY_VOTE_COUNT_REQUEST';
export const VERIFY_VOTE_COUNT_SUCCESS = 'voting/VERIFY_VOTE_COUNT_SUCCESS';
export const VERIFY_VOTE_COUNT_FAILURE = 'voting/VERIFY_VOTE_COUNT_FAILURE';

export const BULK_VOTE_ENTRY_REQUEST = 'voting/BULK_VOTE_ENTRY_REQUEST';
export const BULK_VOTE_ENTRY_SUCCESS = 'voting/BULK_VOTE_ENTRY_SUCCESS';
export const BULK_VOTE_ENTRY_FAILURE = 'voting/BULK_VOTE_ENTRY_FAILURE';

// Candidates
export const GET_CANDIDATES_REQUEST = 'voting/GET_CANDIDATES_REQUEST';
export const GET_CANDIDATES_SUCCESS = 'voting/GET_CANDIDATES_SUCCESS';
export const GET_CANDIDATES_FAILURE = 'voting/GET_CANDIDATES_FAILURE';

export const CREATE_CANDIDATE_REQUEST = 'voting/CREATE_CANDIDATE_REQUEST';
export const CREATE_CANDIDATE_SUCCESS = 'voting/CREATE_CANDIDATE_SUCCESS';
export const CREATE_CANDIDATE_FAILURE = 'voting/CREATE_CANDIDATE_FAILURE';

export const UPDATE_CANDIDATE_REQUEST = 'voting/UPDATE_CANDIDATE_REQUEST';
export const UPDATE_CANDIDATE_SUCCESS = 'voting/UPDATE_CANDIDATE_SUCCESS';
export const UPDATE_CANDIDATE_FAILURE = 'voting/UPDATE_CANDIDATE_FAILURE';

export const DELETE_CANDIDATE_REQUEST = 'voting/DELETE_CANDIDATE_REQUEST';
export const DELETE_CANDIDATE_SUCCESS = 'voting/DELETE_CANDIDATE_SUCCESS';
export const DELETE_CANDIDATE_FAILURE = 'voting/DELETE_CANDIDATE_FAILURE';

// Parties
export const GET_PARTIES_REQUEST = 'voting/GET_PARTIES_REQUEST';
export const GET_PARTIES_SUCCESS = 'voting/GET_PARTIES_SUCCESS';
export const GET_PARTIES_FAILURE = 'voting/GET_PARTIES_FAILURE';

// Election Results
export const GET_ELECTION_RESULTS_REQUEST = 'voting/GET_ELECTION_RESULTS_REQUEST';
export const GET_ELECTION_RESULTS_SUCCESS = 'voting/GET_ELECTION_RESULTS_SUCCESS';
export const GET_ELECTION_RESULTS_FAILURE = 'voting/GET_ELECTION_RESULTS_FAILURE';

export const GENERATE_RESULTS_REQUEST = 'voting/GENERATE_RESULTS_REQUEST';
export const GENERATE_RESULTS_SUCCESS = 'voting/GENERATE_RESULTS_SUCCESS';
export const GENERATE_RESULTS_FAILURE = 'voting/GENERATE_RESULTS_FAILURE';

// Statistics
export const GET_VOTING_STATISTICS_REQUEST = 'voting/GET_VOTING_STATISTICS_REQUEST';
export const GET_VOTING_STATISTICS_SUCCESS = 'voting/GET_VOTING_STATISTICS_SUCCESS';
export const GET_VOTING_STATISTICS_FAILURE = 'voting/GET_VOTING_STATISTICS_FAILURE';

// Committee Entries
export const GET_COMMITTEE_ENTRIES_REQUEST = 'voting/GET_COMMITTEE_ENTRIES_REQUEST';
export const GET_COMMITTEE_ENTRIES_SUCCESS = 'voting/GET_COMMITTEE_ENTRIES_SUCCESS';
export const GET_COMMITTEE_ENTRIES_FAILURE = 'voting/GET_COMMITTEE_ENTRIES_FAILURE';

// Filters
export const SET_VOTE_COUNT_FILTERS = 'voting/SET_VOTE_COUNT_FILTERS';
export const CLEAR_VOTING_ERROR = 'voting/CLEAR_VOTING_ERROR';
