# Generated by Django 4.2.7 on 2025-10-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
        ('electors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceStatistics',
            fields=[
                ('committee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='attendance_stats', serialize=False, to='elections.committee')),
                ('total_electors', models.IntegerField(default=0, help_text='Total electors assigned to this committee')),
                ('total_attended', models.IntegerField(default=0, help_text='Total electors who have attended')),
                ('total_walk_ins', models.IntegerField(default=0, help_text='Total walk-in electors (not in original list)')),
                ('hourly_breakdown', models.JSONField(default=dict, help_text='Attendance count by hour: {hour: count}')),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Attendance Statistics',
                'verbose_name_plural': 'Attendance Statistics',
                'db_table': 'attendance_statistics',
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attended_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when attendance was marked')),
                ('is_walk_in', models.BooleanField(default=False, help_text='Elector was added on voting day (not in original database)')),
                ('notes', models.TextField(blank=True, help_text='Any special notes or issues during attendance')),
                ('device_info', models.JSONField(blank=True, default=dict, help_text='Device info (mobile/desktop, IP, location if available)')),
                ('committee', models.ForeignKey(help_text='Committee where elector attended', on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='elections.committee')),
                ('elector', models.OneToOneField(help_text='Elector who attended (one attendance per elector)', on_delete=django.db.models.deletion.CASCADE, related_name='attendance', to='electors.elector')),
                ('marked_by', models.ForeignKey(help_text='User who marked this attendance', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendances_marked', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Attendance',
                'verbose_name_plural': 'Attendances',
                'db_table': 'attendance',
                'ordering': ['-attended_at'],
                'indexes': [models.Index(fields=['committee', '-attended_at'], name='attendance_committ_41152f_idx'), models.Index(fields=['marked_by'], name='attendance_marked__917650_idx'), models.Index(fields=['-attended_at'], name='attendance_attende_6f4a8a_idx'), models.Index(fields=['elector'], name='attendance_elector_786f6a_idx')],
            },
        ),
    ]
