# Generated by Django 4.2.7 on 2025-11-02 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='is_walk_in',
        ),
    ]
