# Generated by Django 4.2.7 on 2025-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0003_attendance_status_and_multi_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('ATTENDED', 'Attended'), ('PENDING', 'Pending')], db_index=True, default='ATTENDED', help_text='Attendance status (attended or pending)', max_length=20),
        ),
    ]
