# Generated by Django 4.2.7 on 2025-11-19 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendees', '0004_alter_attendance_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendancestatistics',
            name='total_walk_ins',
        ),
    ]
