# Generated by Django 4.2.7 on 2025-10-24 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Elector',
            fields=[
                ('koc_id', models.CharField(help_text='KOC Employee Number (unique identifier)', max_length=20, primary_key=True, serialize=False)),
                ('name_first', models.CharField(help_text='First name', max_length=50)),
                ('name_second', models.CharField(blank=True, help_text='Second name', max_length=50)),
                ('name_third', models.CharField(blank=True, help_text='Third name', max_length=50)),
                ('name_fourth', models.CharField(blank=True, help_text='Fourth name', max_length=50)),
                ('name_fifth', models.CharField(blank=True, help_text='Fifth name', max_length=50)),
                ('name_before_last', models.CharField(blank=True, help_text='Family/Tribe name (name before last)', max_length=50)),
                ('name_last', models.CharField(help_text='Last name (surname)', max_length=50)),
                ('designation', models.CharField(blank=True, help_text='Job Title', max_length=100)),
                ('section', models.CharField(blank=True, help_text='Department', max_length=100)),
                ('extension', models.CharField(blank=True, help_text='Office Phone Extension', max_length=20)),
                ('mobile', models.CharField(blank=True, help_text='Mobile phone number', max_length=15)),
                ('area', models.CharField(blank=True, help_text='Geographic area', max_length=100)),
                ('team', models.CharField(blank=True, help_text='Organizational team', max_length=100)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Gender (for committee assignment)', max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Eligible to vote')),
                ('is_walk_in', models.BooleanField(default=False, help_text='Added on voting day (not in original import)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(help_text='Assigned voting committee', on_delete=django.db.models.deletion.PROTECT, related_name='electors', to='elections.committee')),
            ],
            options={
                'verbose_name': 'Elector',
                'verbose_name_plural': 'Electors',
                'db_table': 'electors',
                'ordering': ['name_first', 'name_last'],
                'indexes': [models.Index(fields=['koc_id'], name='electors_koc_id_f82322_idx'), models.Index(fields=['name_first', 'name_last'], name='electors_name_fi_faca83_idx'), models.Index(fields=['name_before_last'], name='electors_name_be_a09218_idx'), models.Index(fields=['committee'], name='electors_committ_e1ca89_idx'), models.Index(fields=['team'], name='electors_team_b99939_idx'), models.Index(fields=['section'], name='electors_section_671228_idx'), models.Index(fields=['mobile'], name='electors_mobile_eda9ec_idx'), models.Index(fields=['gender'], name='electors_gender_929b88_idx'), models.Index(fields=['is_active'], name='electors_is_acti_b6acfd_idx')],
            },
        ),
    ]
