# Generated by Django 4.2.7 on 2025-11-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='name_sixth',
            field=models.CharField(blank=True, help_text='Sixth name', max_length=50),
        ),
        migrations.AlterField(
            model_name='elector',
            name='name_before_last',
            field=models.CharField(blank=True, help_text='Sub-tribe name (name before last)', max_length=50),
        ),
        migrations.AlterField(
            model_name='elector',
            name='name_last',
            field=models.CharField(help_text='Last name (surname/main tribe)', max_length=50),
        ),
    ]
