# Generated by Django 4.2.7 on 2025-11-01 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0003_rename_name_fields'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='elector',
            name='electors_name_fi_faca83_idx',
        ),
        migrations.RemoveIndex(
            model_name='elector',
            name='electors_name_be_a09218_idx',
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['name_first', 'family_name'], name='electors_name_fi_82e61c_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['sub_family_name'], name='electors_sub_fam_cfd3fd_idx'),
        ),
    ]
