# Generated by Django 4.2.7 on 2025-11-01 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electors', '0004_remove_elector_electors_name_fi_faca83_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elector',
            name='is_walk_in',
        ),
        migrations.AddField(
            model_name='elector',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this elector', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='electors_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='elector',
            name='is_approved',
            field=models.BooleanField(default=True, help_text='Elector approved by admin (for newly added electors)'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['is_approved'], name='electors_is_appr_14b2ad_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['created_by'], name='electors_created_a8fec7_idx'),
        ),
    ]
