# Generated by Django 4.2.7 on 2025-11-08 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0005_remove_walk_in_add_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='elector',
            name='sub_team',
            field=models.CharField(blank=True, help_text='Organizational sub team', max_length=100),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['sub_team'], name='electors_sub_tea_b22b3e_idx'),
        ),
    ]
