# Generated by Django 4.2.7 on 2025-11-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0007_rename_team_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elector',
            name='department',
            field=models.CharField(blank=True, help_text='Organizational department', max_length=100),
        ),
        migrations.AlterField(
            model_name='elector',
            name='team',
            field=models.CharField(blank=True, help_text='Organizational team', max_length=100),
        ),
    ]
