# Generated by Django 4.2.7 on 2025-11-18 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electors', '0008_alter_elector_department_alter_elector_team'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['committee', 'is_active'], name='electors_committee_active_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['department', 'is_active'], name='electors_dept_active_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['team', 'is_active'], name='electors_team_active_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['section', 'is_active'], name='electors_section_active_idx'),
        ),
        migrations.AddIndex(
            model_name='elector',
            index=models.Index(fields=['is_active', 'is_approved'], name='electors_active_approved_idx'),
        ),
    ]
