# Generated by Django 4.2.7 on 2025-10-27 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('electors', '0001_initial'),
        ('elections', '0003_rename_voting_date_to_election_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Party name', max_length=200)),
                ('abbreviation', models.CharField(blank=True, help_text='Party abbreviation (e.g., GOP, DEM)', max_length=20)),
                ('color', models.CharField(default='#000000', help_text='Party color in hex format', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Party description')),
                ('is_active', models.BooleanField(default=True, help_text='Is party active in election?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='Election this party is participating in', on_delete=django.db.models.deletion.CASCADE, related_name='parties', to='elections.election')),
            ],
            options={
                'verbose_name': 'Party',
                'verbose_name_plural': 'Parties',
                'db_table': 'parties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_number', models.IntegerField(help_text='Candidate number on ballot')),
                ('party_affiliation', models.CharField(blank=True, help_text='Party name (for independent or backup)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Is candidate still in race?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(help_text='Election this candidate is running in', on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='elections.election')),
                ('elector', models.ForeignKey(help_text='Elector who is a candidate', on_delete=django.db.models.deletion.CASCADE, related_name='candidacies', to='electors.elector')),
                ('party', models.ForeignKey(blank=True, help_text='Party affiliation (null for independent)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidates', to='candidates.party')),
            ],
            options={
                'verbose_name': 'Candidate',
                'verbose_name_plural': 'Candidates',
                'db_table': 'candidates',
                'ordering': ['candidate_number'],
            },
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['election', 'is_active'], name='parties_electio_6efa7a_idx'),
        ),
        migrations.AddIndex(
            model_name='party',
            index=models.Index(fields=['name'], name='parties_name_19bc50_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='party',
            unique_together={('election', 'name')},
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'candidate_number'], name='candidates_electio_75e70a_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['election', 'is_active'], name='candidates_electio_09b174_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['candidate_number'], name='candidates_candida_79d0b1_idx'),
        ),
        migrations.AddIndex(
            model_name='candidate',
            index=models.Index(fields=['elector'], name='candidates_elector_5ec778_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='candidate',
            unique_together={('election', 'elector')},
        ),
    ]
