# Generated by Django 4.2.7 on 2025-11-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_remove_elector_relationship'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='candidate',
            name='candidates_candida_79d0b1_idx',
        ),
        migrations.RenameIndex(
            model_name='candidate',
            new_name='candidates_name_2966a8_idx',
            old_name='candidates_name_e2ba76_idx',
        ),
    ]
