# Generated by Django 4.2.7 on 2025-10-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electors', '__first__'),
        ('candidates', '__first__'),  # Candidates app must exist first
    ]

    operations = [
        # NOTE: Candidate and Party models were moved to candidates app
        # They are created in candidates/migrations/0001_initial_candidates_models.py
        # and deleted from voting app in voting/migrations/0002_...
        migrations.CreateModel(
            name='VoteCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(default=0, help_text='Number of votes received')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('SUBMITTED', 'Submitted'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='DRAFT', help_text='Vote count status', max_length=20)),
                ('is_verified', models.BooleanField(default=False, help_text='Has been verified by admin')),
                ('verified_at', models.DateTimeField(blank=True, help_text='When vote count was verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes or issues')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('candidate', models.ForeignKey(help_text='Candidate receiving votes', on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='candidates.candidate')),
                ('committee', models.ForeignKey(help_text='Committee reporting votes', on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='elections.committee')),
                ('election', models.ForeignKey(help_text='Election', on_delete=django.db.models.deletion.CASCADE, related_name='vote_counts', to='elections.election')),
                ('entered_by', models.ForeignKey(help_text='User who entered vote count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_counts_entered', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified vote count', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_counts_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vote Count',
                'verbose_name_plural': 'Vote Counts',
                'db_table': 'vote_counts',
                'ordering': ['-created_at'],
            },
        ),
        # Party model moved to candidates app
        migrations.CreateModel(
            name='ElectionResults',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PRELIMINARY', 'Preliminary'), ('FINAL', 'Final'), ('PUBLISHED', 'Published')], default='DRAFT', help_text='Results status', max_length=20)),
                ('total_registered_electors', models.IntegerField(default=0, help_text='Total electors registered')),
                ('total_attendance', models.IntegerField(default=0, help_text='Total electors who attended')),
                ('total_ballots_cast', models.IntegerField(default=0, help_text='Total ballots cast')),
                ('total_valid_ballots', models.IntegerField(default=0, help_text='Total valid ballots')),
                ('total_invalid_ballots', models.IntegerField(default=0, help_text='Total invalid/spoiled ballots')),
                ('turnout_percentage', models.FloatField(default=0.0, help_text='Turnout percentage')),
                ('results_data', models.JSONField(default=dict, help_text='Complete results data as JSON')),
                ('generated_at', models.DateTimeField(blank=True, help_text='When results were generated', null=True)),
                ('published_at', models.DateTimeField(blank=True, help_text='When results were published', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.OneToOneField(help_text='Election', on_delete=django.db.models.deletion.CASCADE, related_name='results', to='elections.election')),
                ('generated_by', models.ForeignKey(help_text='User who generated results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_results_generated', to=settings.AUTH_USER_MODEL)),
                ('published_by', models.ForeignKey(blank=True, help_text='User who published results', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='election_results_published', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election Results',
                'verbose_name_plural': 'Election Results',
                'db_table': 'election_results',
            },
        ),
        migrations.CreateModel(
            name='CommitteeVoteEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('VERIFIED', 'Verified')], default='IN_PROGRESS', help_text='Entry status', max_length=20)),
                ('total_ballots_cast', models.IntegerField(default=0, help_text='Total ballots cast in this committee')),
                ('invalid_ballots', models.IntegerField(default=0, help_text='Number of invalid/spoiled ballots')),
                ('valid_ballots', models.IntegerField(default=0, help_text='Number of valid ballots')),
                ('completed_at', models.DateTimeField(blank=True, help_text='When entry was completed', null=True)),
                ('verified_at', models.DateTimeField(blank=True, help_text='When verified', null=True)),
                ('notes', models.TextField(blank=True, help_text='Notes about vote counting')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('committee', models.ForeignKey(help_text='Committee', on_delete=django.db.models.deletion.CASCADE, related_name='vote_entries', to='elections.committee')),
                ('election', models.ForeignKey(help_text='Election', on_delete=django.db.models.deletion.CASCADE, related_name='committee_entries', to='elections.election')),
                ('entered_by', models.ForeignKey(help_text='User who entered votes', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_entries', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, help_text='User who verified', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='committee_entries_verified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Committee Vote Entry',
                'verbose_name_plural': 'Committee Vote Entries',
                'db_table': 'committee_vote_entries',
                'ordering': ['-created_at'],
            },
        ),
        # Party field on Candidate is handled in candidates app migrations
        migrations.CreateModel(
            name='VoteCountAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected'), ('DELETED', 'Deleted')], help_text='Action performed', max_length=20)),
                ('old_value', models.IntegerField(blank=True, help_text='Previous vote count', null=True)),
                ('new_value', models.IntegerField(blank=True, help_text='New vote count', null=True)),
                ('notes', models.TextField(blank=True, help_text='Reason for change')),
                ('ip_address', models.GenericIPAddressField(blank=True, help_text='IP address of user', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='User who performed action', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vote_audit_log', to=settings.AUTH_USER_MODEL)),
                ('vote_count', models.ForeignKey(help_text='Associated vote count', on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='voting.votecount')),
            ],
            options={
                'verbose_name': 'Vote Count Audit',
                'verbose_name_plural': 'Vote Count Audit',
                'db_table': 'vote_count_audit',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['vote_count', '-created_at'], name='vote_count__vote_co_69d6e0_idx'), models.Index(fields=['user'], name='vote_count__user_id_e9ffac_idx'), models.Index(fields=['action'], name='vote_count__action_2a0233_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='votecount',
            index=models.Index(fields=['election', 'status'], name='vote_counts_electio_2036e7_idx'),
        ),
        migrations.AddIndex(
            model_name='votecount',
            index=models.Index(fields=['committee', 'status'], name='vote_counts_committ_83d4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='votecount',
            index=models.Index(fields=['candidate'], name='vote_counts_candida_4fd7d4_idx'),
        ),
        migrations.AddIndex(
            model_name='votecount',
            index=models.Index(fields=['is_verified'], name='vote_counts_is_veri_c29622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='votecount',
            unique_together={('committee', 'candidate')},
        ),
        migrations.AddIndex(
            model_name='committeevoteentry',
            index=models.Index(fields=['election', 'status'], name='committee_v_electio_048696_idx'),
        ),
        migrations.AddIndex(
            model_name='committeevoteentry',
            index=models.Index(fields=['committee'], name='committee_v_committ_0a6694_idx'),
        ),
        migrations.AddIndex(
            model_name='committeevoteentry',
            index=models.Index(fields=['status'], name='committee_v_status_56dc2a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='committeevoteentry',
            unique_together={('election', 'committee')},
        ),
        # Candidate and Party indexes/constraints are handled in candidates app migrations
    ]
