# Generated by Django 4.2.7 on 2025-10-27 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '__first__'),
        ('voting', '0001_initial'),
    ]

    operations = [
        # NOTE: Candidate and Party models were never created in voting app
        # They exist in candidates app. Migration 0001 already references candidates.candidate
        # This migration is kept for historical consistency but is effectively a no-op
        # The AlterField operation is not needed since 0001 already references candidates.candidate
    ]
