# Generated by Django 4.2.7 on 2025-11-19 07:19

import apps.demos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('elections', '0009_fix_committee_code_unique_and_gender_default'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoSeedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('current_phase', models.CharField(blank=True, max_length=32)),
                ('config', models.JSONField(default=dict)),
                ('progress', models.JSONField(blank=True, default=apps.demos.models.default_progress)),
                ('errors', models.JSONField(blank=True, default=list)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('election', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='demo_seed_jobs', to='elections.election')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
