# Generated by Django 4.2.7 on 2025-11-08 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='analyticssnapshot',
            index=models.Index(fields=['snapshot_type', '-snapshot_date'], name='analytics_s_snapsho_dda57e_idx'),
        ),
        migrations.AddIndex(
            model_name='campaignfinancesnapshot',
            index=models.Index(fields=['period_start', 'period_end'], name='campaign_fi_period__838348_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['user', 'order'], name='dashboard_w_user_id_074448_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboardwidget',
            index=models.Index(fields=['user', 'is_visible'], name='dashboard_w_user_id_60cb5b_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['report_type'], name='generated_r_report__c6ba3d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['status'], name='generated_r_status_a41f66_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['generated_by'], name='generated_r_generat_b6d39d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['-created_at'], name='generated_r_created_c6db14_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedreport',
            index=models.Index(fields=['expires_at'], name='generated_r_expires_0d2cb9_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['report_type'], name='report_temp_report__568538_idx'),
        ),
        migrations.AddIndex(
            model_name='reporttemplate',
            index=models.Index(fields=['is_active'], name='report_temp_is_acti_2cb562_idx'),
        ),
    ]
