# Generated by Django 4.2.7 on 2025-10-26 16:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('electors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuaranteeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Group name (e.g., "Close Friends")', max_length=100)),
                ('color', models.CharField(default='#1976d2', help_text='Hex color for UI display (e.g., #FF5722)', max_length=7)),
                ('description', models.TextField(blank=True, help_text='Optional description')),
                ('order', models.IntegerField(default=0, help_text='Display order (lower = first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(help_text='User who created this group', on_delete=django.db.models.deletion.CASCADE, related_name='guarantee_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantee Group',
                'verbose_name_plural': 'Guarantee Groups',
                'db_table': 'guarantee_groups',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Guarantee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('STRONG', 'Strong'), ('MEDIUM', 'Medium'), ('WEAK', 'Weak')], default='MEDIUM', help_text='Strength of the guarantee', max_length=10)),
                ('additional_mobile', models.CharField(blank=True, help_text='Additional phone number', max_length=15)),
                ('whatsapp_number', models.CharField(blank=True, help_text='WhatsApp number if different from mobile', max_length=15)),
                ('quick_note', models.CharField(blank=True, help_text='Short note visible in list view', max_length=200)),
                ('last_contact_date', models.DateField(blank=True, help_text='Last time contacted', null=True)),
                ('follow_up_required', models.BooleanField(default=False, help_text='Needs follow-up contact')),
                ('follow_up_date', models.DateField(blank=True, help_text='Scheduled follow-up date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='When guarantee was collected')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('elector', models.ForeignKey(help_text='Elector who gave the guarantee', on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to='electors.elector')),
                ('group', models.ForeignKey(blank=True, help_text='Custom group (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantees', to='guarantees.guaranteegroup')),
                ('user', models.ForeignKey(help_text='User who collected this guarantee', on_delete=django.db.models.deletion.CASCADE, related_name='guarantees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantee',
                'verbose_name_plural': 'Guarantees',
                'db_table': 'guarantees',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(help_text='Note content')),
                ('is_important', models.BooleanField(default=False, help_text='Flag as important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantee', models.ForeignKey(help_text='Associated guarantee', on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='guarantees.guarantee')),
                ('user', models.ForeignKey(help_text='User who created this note', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantee Note',
                'verbose_name_plural': 'Guarantee Notes',
                'db_table': 'guarantee_notes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guarantee', '-created_at'], name='guarantee_n_guarant_833c49_idx'), models.Index(fields=['user'], name='guarantee_n_user_id_f91569_idx'), models.Index(fields=['is_important'], name='guarantee_n_is_impo_ed6cec_idx')],
            },
        ),
        migrations.CreateModel(
            name='GuaranteeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('GROUP_CHANGED', 'Group Changed'), ('NOTE_ADDED', 'Note Added'), ('CONTACT_UPDATED', 'Contact Updated'), ('DELETED', 'Deleted')], help_text='Type of action', max_length=20)),
                ('old_value', models.TextField(blank=True, help_text='Previous value (JSON)')),
                ('new_value', models.TextField(blank=True, help_text='New value (JSON)')),
                ('description', models.TextField(blank=True, help_text='Human-readable description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('guarantee', models.ForeignKey(help_text='Associated guarantee', on_delete=django.db.models.deletion.CASCADE, related_name='history', to='guarantees.guarantee')),
                ('user', models.ForeignKey(help_text='User who made the change', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='guarantee_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Guarantee History',
                'verbose_name_plural': 'Guarantee History',
                'db_table': 'guarantee_history',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['guarantee', '-created_at'], name='guarantee_h_guarant_52b59d_idx'), models.Index(fields=['user'], name='guarantee_h_user_id_bc9ab7_idx'), models.Index(fields=['action'], name='guarantee_h_action_c1ca9b_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='guaranteegroup',
            index=models.Index(fields=['user', 'order'], name='guarantee_g_user_id_aac47a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guaranteegroup',
            unique_together={('user', 'name')},
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['user', 'status'], name='guarantees_user_id_428238_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['user', 'group'], name='guarantees_user_id_2323f7_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['user', 'created_at'], name='guarantees_user_id_aaf0a8_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['elector'], name='guarantees_elector_95c3ea_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['follow_up_required', 'follow_up_date'], name='guarantees_follow__d13a78_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='guarantee',
            unique_together={('user', 'elector')},
        ),
    ]
