# Generated by Django 4.2.7 on 2025-11-04 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('guarantees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guarantee',
            name='confirmation_note',
            field=models.TextField(blank=True, help_text='Note about confirmation status'),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='confirmation_status',
            field=models.CharField(choices=[('PENDING', 'Pending Confirmation'), ('CONFIRMED', 'Confirmed'), ('DECLINED', 'Declined/Changed Mind'), ('UNREACHABLE', 'Unreachable')], db_index=True, default='PENDING', help_text='Confirmation status of the guarantee', max_length=20),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='last_confirmation_date',
            field=models.DateTimeField(blank=True, help_text='When guarantee was last confirmed', null=True),
        ),
        migrations.AddField(
            model_name='guarantee',
            name='last_confirmed_by',
            field=models.ForeignKey(blank=True, help_text='User who last confirmed this guarantee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='confirmed_guarantees', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guaranteehistory',
            name='action',
            field=models.CharField(choices=[('CREATED', 'Created'), ('UPDATED', 'Updated'), ('STATUS_CHANGED', 'Status Changed'), ('GROUP_CHANGED', 'Group Changed'), ('NOTE_ADDED', 'Note Added'), ('CONTACT_UPDATED', 'Contact Updated'), ('CONFIRMATION_CHANGED', 'Confirmation Changed'), ('DELETED', 'Deleted')], help_text='Type of action', max_length=20),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['confirmation_status', 'status'], name='guarantees_confirm_c5ec71_idx'),
        ),
        migrations.AddIndex(
            model_name='guarantee',
            index=models.Index(fields=['user', 'confirmation_status'], name='guarantees_user_id_fa56d1_idx'),
        ),
    ]
