# Generated by Django 4.2.7 on 2025-11-07 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0002_add_confirmation_tracking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='guarantee',
            old_name='additional_mobile',
            new_name='alternate_phone',
        ),
        migrations.RenameField(
            model_name='guarantee',
            old_name='whatsapp_number',
            new_name='primary_phone',
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='alternate_phone',
            field=models.CharField(blank=True, help_text='Alternate contact phone number', max_length=15),
        ),
        migrations.AlterField(
            model_name='guarantee',
            name='primary_phone',
            field=models.CharField(blank=True, help_text='Primary contact phone number for follow-ups', max_length=15),
        ),
    ]
