# Generated by Django 4.2.7 on 2025-11-09 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0009_guarantee_status_refactor'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='guarantee',
            new_name='guarantees_user_id_4c9194_idx',
            old_name='guarantees_user_guarantee_idx',
        ),
        migrations.RenameIndex(
            model_name='guarantee',
            new_name='guarantees_confirm_abd5e1_idx',
            old_name='guarantees_conf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='guarantee',
            new_name='guarantees_user_id_fa56d1_idx',
            old_name='guarantees_user_confirm_idx',
        ),
    ]
