# Generated by Django 4.2.7 on 2025-11-17 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guarantees', '0011_guarantee_mobile_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guarantee',
            name='mobile',
            field=models.CharField(blank=True, help_text='Contact phone number for follow-ups', max_length=15),
        ),
    ]
