# Generated by Django 4.2.7 on 2025-10-24 17:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Election',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Election name', max_length=255)),
                ('description', models.TextField(blank=True)),
                ('voting_mode', models.CharField(choices=[('FULL_PARTY', 'Full Party Ticket'), ('MIXED', 'Mixed Ticket'), ('BOTH', 'Both Options')], default='BOTH', help_text='Voting mode: full party, mixed, or both', max_length=20)),
                ('max_candidates_per_ballot', models.IntegerField(default=19, help_text='Maximum candidates a voter can select')),
                ('allow_partial_voting', models.BooleanField(default=True, help_text='Allow voting for less than max candidates')),
                ('minimum_votes_required', models.IntegerField(default=1, help_text='Minimum candidates required per ballot')),
                ('status', models.CharField(choices=[('SETUP', 'Setup'), ('GUARANTEE_PHASE', 'Guarantee Collection Phase'), ('VOTING_DAY', 'Voting Day'), ('COUNTING', 'Counting in Progress'), ('CLOSED', 'Closed')], default='SETUP', help_text='Current election phase', max_length=20)),
                ('guarantee_start_date', models.DateField(blank=True, help_text='When guarantee collection starts', null=True)),
                ('guarantee_end_date', models.DateField(blank=True, help_text='When guarantee collection ends', null=True)),
                ('voting_date', models.DateField(blank=True, help_text='Voting day date', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elections_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Election',
                'verbose_name_plural': 'Elections',
                'db_table': 'elections',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Committee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Committee code (e.g., EK-II, FC#28)', max_length=20, unique=True)),
                ('name', models.CharField(help_text='Committee name', max_length=255)),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], help_text='Gender segregation', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_users', models.ManyToManyField(blank=True, help_text='Users assigned to this committee for voting day', related_name='assigned_committees', to=settings.AUTH_USER_MODEL)),
                ('election', models.ForeignKey(help_text='Election this committee belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='committees', to='elections.election')),
            ],
            options={
                'verbose_name': 'Committee',
                'verbose_name_plural': 'Committees',
                'db_table': 'committees',
                'ordering': ['code'],
                'indexes': [models.Index(fields=['election', 'code'], name='committees_electio_f8291b_idx'), models.Index(fields=['gender'], name='committees_gender_556c95_idx'), models.Index(fields=['code'], name='committees_code_2e9fd6_idx')],
            },
        ),
    ]
