# Generated by Django 4.2.7 on 2025-10-27 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='guarantee_end_date',
        ),
        migrations.RemoveField(
            model_name='election',
            name='guarantee_start_date',
        ),
    ]
