# Generated by Django 4.2.7 on 2025-10-27 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0002_remove_guarantee_dates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='election',
            name='voting_date',
        ),
        migrations.AddField(
            model_name='election',
            name='election_date',
            field=models.DateField(blank=True, help_text='Election day date', null=True),
        ),
    ]
