# Generated by Django 4.2.7 on 2025-11-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0005_add_election_assigned_users'),
    ]

    operations = [
        migrations.AlterField(
            model_name='committee',
            name='gender',
            field=models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('MIXED', 'Mixed')], help_text='Gender segregation', max_length=10),
        ),
    ]
