# Generated by Django 4.2.7 on 2025-11-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elections', '0007_rename_assigned_users_to_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='committee',
            name='electors_from',
            field=models.IntegerField(blank=True, help_text='Starting elector number for this committee', null=True),
        ),
        migrations.AddField(
            model_name='committee',
            name='electors_to',
            field=models.IntegerField(blank=True, help_text='Ending elector number for this committee', null=True),
        ),
    ]
